### ISSUE TITLE
:art: Improvements and Enhancements

### ISSUE THREAD

**Issue by nejidevelops** [George7h/Module-1-capstone-project#2]
## Improvements

Looking at your code, there are a number of issues pointed out that need improvement and they will help make your code look professional :sunglasses: 

![Screenshot from 2023-06-30 10-21-45](https://github.com/George7h/Module-1-capstone-project/assets/79839603/0a7c544f-5e26-4163-b3ab-35f8cef1948d)

**Looking at the screenshot above**
- Try adding  some interactivity with your cards, to help improve UX of the users. You can add some hover effects to the card an example you can have a translate of the card when hovered, here is a link on CSS translate [WebDocs Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate) or you can add some border to it when hovered.

## Acceptance Criteria
- [x] Use of CSS hover pseudo-selector

***Let's take your code to the next level :sunglasses: , you can do it :100: :muscle:***

**Comment by George7h** [comment]
Thank you so much. I have done the necessary changes and thank you for the kind words.

<img src="https://media2.giphy.com/media/nqtCrUwM148ZVKQtlu/giphy.gif"/>

Please feel free to check it 😄

**Comment by George7h** [comment]
Thank you so much. I have done the necessary changes and thank you for the kind words.

<img src="https://media2.giphy.com/media/nqtCrUwM148ZVKQtlu/giphy.gif"/>

Please feel free to check it 😄
