### ISSUE TITLE
Show more button

### ISSUE THREAD

**Issue by AlyAtalla** [George7h/Module-1-capstone-project#3]
Hi George, Excellent work on your project, there are some issues you may need to address : 
- the show more button doesn't work in reverse, so it works to show more but once it is expanded it doesn't go back or "show less".
-CSS code needs to be more organized to make it easier to read.

**Comment by George7h** [comment]
Thank you so much for the suggestions. I will make the improvements. 😄 

<img src="https://media2.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>
